[GitHub Actions] buildtest.yml: use -Wno-transparent-union for sparse build
Sparse is broken with 6.2-rc1

./include/linux/mm.h:1288:58: error: attribute __transparent_union__

This error was added by commit 449c796768c9 ("mm: teach
release_pages() to take an array of encoded page pointers too") from
our very own Linus Torvals who added the comment 'The transparent
union syntax for this kind of "any of these argument types" is all
kinds of ugly, so look away.'

let's remove the transparent-union type and move on.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>